//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 04:07:49 pmCST 
//


package com.ccm.api.model.ads.vo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelAddresses">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HotelAddress" type="{http://www.micros.com/2002A}AddressData" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HotelContacts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HotelContact" type="{http://www.micros.com/2002A}HotelContact" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyLocation", propOrder = {
    "hotelAddresses",
    "hotelContacts"
})
public class PropertyLocation {

    @XmlElement(name = "HotelAddresses", required = true)
    protected PropertyLocation.HotelAddresses hotelAddresses;
    @XmlElement(name = "HotelContacts", required = true)
    protected PropertyLocation.HotelContacts hotelContacts;

    /**
     * Gets the value of the hotelAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyLocation.HotelAddresses }
     *     
     */
    public PropertyLocation.HotelAddresses getHotelAddresses() {
        return hotelAddresses;
    }

    /**
     * Sets the value of the hotelAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyLocation.HotelAddresses }
     *     
     */
    public void setHotelAddresses(PropertyLocation.HotelAddresses value) {
        this.hotelAddresses = value;
    }

    /**
     * Gets the value of the hotelContacts property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyLocation.HotelContacts }
     *     
     */
    public PropertyLocation.HotelContacts getHotelContacts() {
        return hotelContacts;
    }

    /**
     * Sets the value of the hotelContacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyLocation.HotelContacts }
     *     
     */
    public void setHotelContacts(PropertyLocation.HotelContacts value) {
        this.hotelContacts = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HotelAddress" type="{http://www.micros.com/2002A}AddressData" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hotelAddress"
    })
    public static class HotelAddresses {

        @XmlElement(name = "HotelAddress", required = true)
        protected List<AddressData> hotelAddress;

        /**
         * Gets the value of the hotelAddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hotelAddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHotelAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AddressData }
         * 
         * 
         */
        public List<AddressData> getHotelAddress() {
            if (hotelAddress == null) {
                hotelAddress = new ArrayList<AddressData>();
            }
            return this.hotelAddress;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HotelContact" type="{http://www.micros.com/2002A}HotelContact" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hotelContact"
    })
    public static class HotelContacts {

        @XmlElement(name = "HotelContact", required = true)
        protected List<HotelContact> hotelContact;

        /**
         * Gets the value of the hotelContact property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hotelContact property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHotelContact().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HotelContact }
         * 
         * 
         */
        public List<HotelContact> getHotelContact() {
            if (hotelContact == null) {
                hotelContact = new ArrayList<HotelContact>();
            }
            return this.hotelContact;
        }

    }

}
