//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 03:58:32 下午 CST 
//

package com.ccm.oxi.reservation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Reservation complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Reservation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HotelReference" type="{reservation.fidelio.2.0}HotelReference"/>
 *         &lt;element name="roomStayReservation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="confirmationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reservationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reservationOriginatorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mfLegNumbers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originalBookingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="cancellationID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancelOriginatorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cancellationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="StayDateRange" type="{reservation.fidelio.2.0}StayDateRange" minOccurs="0"/>
 *         &lt;element name="GuestCounts" type="{reservation.fidelio.2.0}GuestCounts" minOccurs="0"/>
 *         &lt;element name="ResComments" type="{reservation.fidelio.2.0}ResComments" minOccurs="0"/>
 *         &lt;element name="ResCreditCards" type="{reservation.fidelio.2.0}ResCreditCards" minOccurs="0"/>
 *         &lt;element name="ResGuests" type="{reservation.fidelio.2.0}ResGuests" minOccurs="0"/>
 *         &lt;element name="ResProfiles" type="{reservation.fidelio.2.0}ResProfiles" minOccurs="0"/>
 *         &lt;element name="RoomStays" type="{reservation.fidelio.2.0}RoomStays" minOccurs="0"/>
 *         &lt;element name="SelectedMemberships" type="{reservation.fidelio.2.0}SelectedMemberships" minOccurs="0"/>
 *         &lt;element name="AnticipatedSettlements" type="{reservation.fidelio.2.0}AnticipatedSettlements" minOccurs="0"/>
 *         &lt;element name="SpecialRequests" type="{reservation.fidelio.2.0}SpecialRequests" minOccurs="0"/>
 *         &lt;element name="Services" type="{reservation.fidelio.2.0}Services" minOccurs="0"/>
 *         &lt;element name="OriginalRoutingHops" type="{reservation.fidelio.2.0}OriginalRoutingHops" minOccurs="0"/>
 *         &lt;element name="resCommentRPHs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resProfileRPHs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialRequestRPHs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceRPHs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mfcancellationComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mfupdateDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="mfcomplementary" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="mfImage" type="{reservation.fidelio.2.0}mfImage" minOccurs="0"/>
 *         &lt;element name="mfHurdleRate" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="mfYieldable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Udfs" type="{reservation.fidelio.2.0}Udfs" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mfShareAction" type="{reservation.fidelio.2.0}mfShareAction" />
 *       &lt;attribute name="mfOtherShareAction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mfReservationAction" type="{reservation.fidelio.2.0}mfReservationAction" />
 *       &lt;attribute name="mfOtherReservationAction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reservation", propOrder = { "hotelReference", "roomStayReservation", "confirmationID", "reservationID", "reservationOriginatorCode", "mfLegNumbers", "originalBookingDate", "cancellationID", "cancelOriginatorCode", "cancellationDate", "stayDateRange", "guestCounts", "resComments", "resCreditCards", "resGuests", "resProfiles", "roomStays", "selectedMemberships", "anticipatedSettlements", "specialRequests", "services", "originalRoutingHops", "resCommentRPHs", "resProfileRPHs", "specialRequestRPHs", "serviceRPHs", "mfcancellationComment", "mfupdateDate", "mfcomplementary", "mfImage", "mfHurdleRate", "mfYieldable", "udfs" })
@XmlRootElement(name = "Reservation")
public class Reservation {

	@XmlElement(name = "HotelReference", required = true)
	protected HotelReference hotelReference;
	protected Boolean roomStayReservation;
	protected String confirmationID;
	protected String reservationID;
	protected String reservationOriginatorCode;
	protected String mfLegNumbers;
	protected XMLGregorianCalendar originalBookingDate;
	protected String cancellationID;
	protected String cancelOriginatorCode;
	protected XMLGregorianCalendar cancellationDate;
	@XmlElement(name = "StayDateRange")
	protected StayDateRange stayDateRange;
	@XmlElement(name = "GuestCounts")
	protected GuestCounts guestCounts;
	@XmlElement(name = "ResComments")
	protected ResComments resComments;
	@XmlElement(name = "ResCreditCards")
	protected ResCreditCards resCreditCards;
	@XmlElement(name = "ResGuests")
	protected ResGuests resGuests;
	@XmlElement(name = "ResProfiles")
	protected ResProfiles resProfiles;
	@XmlElement(name = "RoomStays")
	protected RoomStays roomStays;
	@XmlElement(name = "SelectedMemberships")
	protected SelectedMemberships selectedMemberships;
	@XmlElement(name = "AnticipatedSettlements")
	protected AnticipatedSettlements anticipatedSettlements;
	@XmlElement(name = "SpecialRequests")
	protected SpecialRequests specialRequests;
	@XmlElement(name = "Services")
	protected Services services;
	@XmlElement(name = "OriginalRoutingHops")
	protected OriginalRoutingHops originalRoutingHops;
	protected String resCommentRPHs;
	protected String resProfileRPHs;
	protected String specialRequestRPHs;
	protected String serviceRPHs;
	protected String mfcancellationComment;
	protected XMLGregorianCalendar mfupdateDate;
	protected Integer mfcomplementary;
	protected MfImage mfImage;
	protected Float mfHurdleRate;
	protected String mfYieldable;
	@XmlElement(name = "Udfs")
	protected Udfs udfs;
	@XmlAttribute
	protected MfShareAction mfShareAction;
	@XmlAttribute
	protected String mfOtherShareAction;
	@XmlAttribute
	protected String mfReservationAction;
	@XmlAttribute
	protected String mfOtherReservationAction;

	/**
	 * Gets the value of the hotelReference property.
	 * 
	 * @return possible object is {@link HotelReference }
	 * 
	 */
	public HotelReference getHotelReference() {
		return hotelReference;
	}

	/**
	 * Sets the value of the hotelReference property.
	 * 
	 * @param value
	 *            allowed object is {@link HotelReference }
	 * 
	 */
	public void setHotelReference(HotelReference value) {
		this.hotelReference = value;
	}

	/**
	 * Gets the value of the roomStayReservation property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isRoomStayReservation() {
		return roomStayReservation;
	}

	/**
	 * Sets the value of the roomStayReservation property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setRoomStayReservation(Boolean value) {
		this.roomStayReservation = value;
	}

	/**
	 * Gets the value of the confirmationID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getConfirmationID() {
		return confirmationID;
	}

	/**
	 * Sets the value of the confirmationID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setConfirmationID(String value) {
		this.confirmationID = value;
	}

	/**
	 * Gets the value of the reservationID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReservationID() {
		return reservationID;
	}

	/**
	 * Sets the value of the reservationID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReservationID(String value) {
		this.reservationID = value;
	}

	/**
	 * Gets the value of the reservationOriginatorCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReservationOriginatorCode() {
		return reservationOriginatorCode;
	}

	/**
	 * Sets the value of the reservationOriginatorCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReservationOriginatorCode(String value) {
		this.reservationOriginatorCode = value;
	}

	/**
	 * Gets the value of the mfLegNumbers property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMfLegNumbers() {
		return mfLegNumbers;
	}

	/**
	 * Sets the value of the mfLegNumbers property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMfLegNumbers(String value) {
		this.mfLegNumbers = value;
	}

	/**
	 * Gets the value of the originalBookingDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getOriginalBookingDate() {
		return originalBookingDate;
	}

	/**
	 * Sets the value of the originalBookingDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setOriginalBookingDate(XMLGregorianCalendar value) {
		this.originalBookingDate = value;
	}

	/**
	 * Gets the value of the cancellationID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCancellationID() {
		return cancellationID;
	}

	/**
	 * Sets the value of the cancellationID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCancellationID(String value) {
		this.cancellationID = value;
	}

	/**
	 * Gets the value of the cancelOriginatorCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCancelOriginatorCode() {
		return cancelOriginatorCode;
	}

	/**
	 * Sets the value of the cancelOriginatorCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCancelOriginatorCode(String value) {
		this.cancelOriginatorCode = value;
	}

	/**
	 * Gets the value of the cancellationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCancellationDate() {
		return cancellationDate;
	}

	/**
	 * Sets the value of the cancellationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCancellationDate(XMLGregorianCalendar value) {
		this.cancellationDate = value;
	}

	/**
	 * Gets the value of the stayDateRange property.
	 * 
	 * @return possible object is {@link StayDateRange }
	 * 
	 */
	public StayDateRange getStayDateRange() {
		return stayDateRange;
	}

	/**
	 * Sets the value of the stayDateRange property.
	 * 
	 * @param value
	 *            allowed object is {@link StayDateRange }
	 * 
	 */
	public void setStayDateRange(StayDateRange value) {
		this.stayDateRange = value;
	}

	/**
	 * Gets the value of the guestCounts property.
	 * 
	 * @return possible object is {@link GuestCounts }
	 * 
	 */
	public GuestCounts getGuestCounts() {
		return guestCounts;
	}

	/**
	 * Sets the value of the guestCounts property.
	 * 
	 * @param value
	 *            allowed object is {@link GuestCounts }
	 * 
	 */
	public void setGuestCounts(GuestCounts value) {
		this.guestCounts = value;
	}

	/**
	 * Gets the value of the resComments property.
	 * 
	 * @return possible object is {@link ResComments }
	 * 
	 */
	public ResComments getResComments() {
		return resComments;
	}

	/**
	 * Sets the value of the resComments property.
	 * 
	 * @param value
	 *            allowed object is {@link ResComments }
	 * 
	 */
	public void setResComments(ResComments value) {
		this.resComments = value;
	}

	/**
	 * Gets the value of the resCreditCards property.
	 * 
	 * @return possible object is {@link ResCreditCards }
	 * 
	 */
	public ResCreditCards getResCreditCards() {
		return resCreditCards;
	}

	/**
	 * Sets the value of the resCreditCards property.
	 * 
	 * @param value
	 *            allowed object is {@link ResCreditCards }
	 * 
	 */
	public void setResCreditCards(ResCreditCards value) {
		this.resCreditCards = value;
	}

	/**
	 * Gets the value of the resGuests property.
	 * 
	 * @return possible object is {@link ResGuests }
	 * 
	 */
	public ResGuests getResGuests() {
		return resGuests;
	}

	/**
	 * Sets the value of the resGuests property.
	 * 
	 * @param value
	 *            allowed object is {@link ResGuests }
	 * 
	 */
	public void setResGuests(ResGuests value) {
		this.resGuests = value;
	}

	/**
	 * Gets the value of the resProfiles property.
	 * 
	 * @return possible object is {@link ResProfiles }
	 * 
	 */
	public ResProfiles getResProfiles() {
		return resProfiles;
	}

	/**
	 * Sets the value of the resProfiles property.
	 * 
	 * @param value
	 *            allowed object is {@link ResProfiles }
	 * 
	 */
	public void setResProfiles(ResProfiles value) {
		this.resProfiles = value;
	}

	/**
	 * Gets the value of the roomStays property.
	 * 
	 * @return possible object is {@link RoomStays }
	 * 
	 */
	public RoomStays getRoomStays() {
		return roomStays;
	}

	/**
	 * Sets the value of the roomStays property.
	 * 
	 * @param value
	 *            allowed object is {@link RoomStays }
	 * 
	 */
	public void setRoomStays(RoomStays value) {
		this.roomStays = value;
	}

	/**
	 * Gets the value of the selectedMemberships property.
	 * 
	 * @return possible object is {@link SelectedMemberships }
	 * 
	 */
	public SelectedMemberships getSelectedMemberships() {
		return selectedMemberships;
	}

	/**
	 * Sets the value of the selectedMemberships property.
	 * 
	 * @param value
	 *            allowed object is {@link SelectedMemberships }
	 * 
	 */
	public void setSelectedMemberships(SelectedMemberships value) {
		this.selectedMemberships = value;
	}

	/**
	 * Gets the value of the anticipatedSettlements property.
	 * 
	 * @return possible object is {@link AnticipatedSettlements }
	 * 
	 */
	public AnticipatedSettlements getAnticipatedSettlements() {
		return anticipatedSettlements;
	}

	/**
	 * Sets the value of the anticipatedSettlements property.
	 * 
	 * @param value
	 *            allowed object is {@link AnticipatedSettlements }
	 * 
	 */
	public void setAnticipatedSettlements(AnticipatedSettlements value) {
		this.anticipatedSettlements = value;
	}

	/**
	 * Gets the value of the specialRequests property.
	 * 
	 * @return possible object is {@link SpecialRequests }
	 * 
	 */
	public SpecialRequests getSpecialRequests() {
		return specialRequests;
	}

	/**
	 * Sets the value of the specialRequests property.
	 * 
	 * @param value
	 *            allowed object is {@link SpecialRequests }
	 * 
	 */
	public void setSpecialRequests(SpecialRequests value) {
		this.specialRequests = value;
	}

	/**
	 * Gets the value of the services property.
	 * 
	 * @return possible object is {@link Services }
	 * 
	 */
	public Services getServices() {
		return services;
	}

	/**
	 * Sets the value of the services property.
	 * 
	 * @param value
	 *            allowed object is {@link Services }
	 * 
	 */
	public void setServices(Services value) {
		this.services = value;
	}

	/**
	 * Gets the value of the originalRoutingHops property.
	 * 
	 * @return possible object is {@link OriginalRoutingHops }
	 * 
	 */
	public OriginalRoutingHops getOriginalRoutingHops() {
		return originalRoutingHops;
	}

	/**
	 * Sets the value of the originalRoutingHops property.
	 * 
	 * @param value
	 *            allowed object is {@link OriginalRoutingHops }
	 * 
	 */
	public void setOriginalRoutingHops(OriginalRoutingHops value) {
		this.originalRoutingHops = value;
	}

	/**
	 * Gets the value of the resCommentRPHs property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResCommentRPHs() {
		return resCommentRPHs;
	}

	/**
	 * Sets the value of the resCommentRPHs property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResCommentRPHs(String value) {
		this.resCommentRPHs = value;
	}

	/**
	 * Gets the value of the resProfileRPHs property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResProfileRPHs() {
		return resProfileRPHs;
	}

	/**
	 * Sets the value of the resProfileRPHs property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResProfileRPHs(String value) {
		this.resProfileRPHs = value;
	}

	/**
	 * Gets the value of the specialRequestRPHs property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpecialRequestRPHs() {
		return specialRequestRPHs;
	}

	/**
	 * Sets the value of the specialRequestRPHs property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSpecialRequestRPHs(String value) {
		this.specialRequestRPHs = value;
	}

	/**
	 * Gets the value of the serviceRPHs property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getServiceRPHs() {
		return serviceRPHs;
	}

	/**
	 * Sets the value of the serviceRPHs property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setServiceRPHs(String value) {
		this.serviceRPHs = value;
	}

	/**
	 * Gets the value of the mfcancellationComment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMfcancellationComment() {
		return mfcancellationComment;
	}

	/**
	 * Sets the value of the mfcancellationComment property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMfcancellationComment(String value) {
		this.mfcancellationComment = value;
	}

	/**
	 * Gets the value of the mfupdateDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getMfupdateDate() {
		return mfupdateDate;
	}

	/**
	 * Sets the value of the mfupdateDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setMfupdateDate(XMLGregorianCalendar value) {
		this.mfupdateDate = value;
	}

	/**
	 * Gets the value of the mfcomplementary property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer isMfcomplementary() {
		return mfcomplementary;
	}

	/**
	 * Sets the value of the mfcomplementary property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setMfcomplementary(Integer value) {
		this.mfcomplementary = value;
	}

	/**
	 * Gets the value of the mfImage property.
	 * 
	 * @return possible object is {@link MfImage }
	 * 
	 */
	public MfImage getMfImage() {
		return mfImage;
	}

	/**
	 * Sets the value of the mfImage property.
	 * 
	 * @param value
	 *            allowed object is {@link MfImage }
	 * 
	 */
	public void setMfImage(MfImage value) {
		this.mfImage = value;
	}

	/**
	 * Gets the value of the mfHurdleRate property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMfHurdleRate() {
		return mfHurdleRate;
	}

	/**
	 * Sets the value of the mfHurdleRate property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMfHurdleRate(Float value) {
		this.mfHurdleRate = value;
	}

	/**
	 * Gets the value of the mfYieldable property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMfYieldable() {
		return mfYieldable;
	}

	/**
	 * Sets the value of the mfYieldable property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMfYieldable(String value) {
		this.mfYieldable = value;
	}

	/**
	 * Gets the value of the udfs property.
	 * 
	 * @return possible object is {@link Udfs }
	 * 
	 */
	public Udfs getUdfs() {
		return udfs;
	}

	/**
	 * Sets the value of the udfs property.
	 * 
	 * @param value
	 *            allowed object is {@link Udfs }
	 * 
	 */
	public void setUdfs(Udfs value) {
		this.udfs = value;
	}

	/**
	 * Gets the value of the mfShareAction property.
	 * 
	 * @return possible object is {@link MfShareAction }
	 * 
	 */
	public MfShareAction getMfShareAction() {
		return mfShareAction;
	}

	/**
	 * Sets the value of the mfShareAction property.
	 * 
	 * @param value
	 *            allowed object is {@link MfShareAction }
	 * 
	 */
	public void setMfShareAction(MfShareAction value) {
		this.mfShareAction = value;
	}

	/**
	 * Gets the value of the mfOtherShareAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMfOtherShareAction() {
		return mfOtherShareAction;
	}

	/**
	 * Sets the value of the mfOtherShareAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMfOtherShareAction(String value) {
		this.mfOtherShareAction = value;
	}

	/**
	 * Gets the value of the mfReservationAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMfReservationAction() {
		return mfReservationAction;
	}

	/**
	 * Sets the value of the mfReservationAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMfReservationAction(String value) {
		this.mfReservationAction = value;
	}

	/**
	 * Gets the value of the mfOtherReservationAction property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMfOtherReservationAction() {
		return mfOtherReservationAction;
	}

	/**
	 * Sets the value of the mfOtherReservationAction property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMfOtherReservationAction(String value) {
		this.mfOtherReservationAction = value;
	}

}
