//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 01:55:28
//


package com.ccm.oxi.ravr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RavrDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RavrDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roomType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="los1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="los2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="los3" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="los4" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="los5" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="los6" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="los7" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mfInactiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="roomAvailability" type="{ravr.fidelio.2.0}roomAvailability" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RavrDetail", propOrder = {
    "roomType",
    "los1",
    "los2",
    "los3",
    "los4",
    "los5",
    "los6",
    "los7"
})
public class RavrDetail {

    @XmlElement(required = true)
    protected String roomType;
    protected Boolean los1;
    protected Boolean los2;
    protected Boolean los3;
    protected Boolean los4;
    protected Boolean los5;
    protected Boolean los6;
    protected Boolean los7;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar mfInactiveDate;
    @XmlAttribute
    protected RoomAvailability roomAvailability;

    /**
     * Gets the value of the roomType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomType(String value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the los1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLos1() {
        return los1;
    }

    /**
     * Sets the value of the los1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLos1(Boolean value) {
        this.los1 = value;
    }

    /**
     * Gets the value of the los2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLos2() {
        return los2;
    }

    /**
     * Sets the value of the los2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLos2(Boolean value) {
        this.los2 = value;
    }

    /**
     * Gets the value of the los3 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLos3() {
        return los3;
    }

    /**
     * Sets the value of the los3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLos3(Boolean value) {
        this.los3 = value;
    }

    /**
     * Gets the value of the los4 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLos4() {
        return los4;
    }

    /**
     * Sets the value of the los4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLos4(Boolean value) {
        this.los4 = value;
    }

    /**
     * Gets the value of the los5 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLos5() {
        return los5;
    }

    /**
     * Sets the value of the los5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLos5(Boolean value) {
        this.los5 = value;
    }

    /**
     * Gets the value of the los6 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLos6() {
        return los6;
    }

    /**
     * Sets the value of the los6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLos6(Boolean value) {
        this.los6 = value;
    }

    /**
     * Gets the value of the los7 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLos7() {
        return los7;
    }

    /**
     * Sets the value of the los7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLos7(Boolean value) {
        this.los7 = value;
    }

    /**
     * Gets the value of the mfInactiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMfInactiveDate() {
        return mfInactiveDate;
    }

    /**
     * Sets the value of the mfInactiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMfInactiveDate(XMLGregorianCalendar value) {
        this.mfInactiveDate = value;
    }

    /**
     * Gets the value of the roomAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link RoomAvailability }
     *     
     */
    public RoomAvailability getRoomAvailability() {
        return roomAvailability;
    }

    /**
     * Sets the value of the roomAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomAvailability }
     *     
     */
    public void setRoomAvailability(RoomAvailability value) {
        this.roomAvailability = value;
    }

}
