//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 01:53:08  GMT+08:00 
//


package org.opentravel.ota._2003._05;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of hotel search criteria.
 * 
 * <p>Java class for DynamicPkgHotelSearchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DynamicPkgHotelSearchType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05}DynamicPkgSearchType">
 *       &lt;sequence>
 *         &lt;element name="HotelSearchCriteria" type="{http://www.opentravel.org/OTA/2003/05}HotelSearchCriteriaType" minOccurs="0"/>
 *         &lt;element name="HotelReservationIDs" type="{http://www.opentravel.org/OTA/2003/05}HotelReservationIDsType" minOccurs="0"/>
 *         &lt;element ref="{http://www.opentravel.org/OTA/2003/05}TPA_Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RequestType" type="{http://www.opentravel.org/OTA/2003/05}HotelComponentSearchType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DynamicPkgHotelSearchType", propOrder = {
    "hotelSearchCriteria",
    "hotelReservationIDs",
    "tpaExtensions"
})
public class DynamicPkgHotelSearchType
    extends DynamicPkgSearchType
{

    @XmlElement(name = "HotelSearchCriteria")
    protected HotelSearchCriteriaType hotelSearchCriteria;
    @XmlElement(name = "HotelReservationIDs")
    protected HotelReservationIDsType hotelReservationIDs;
    @XmlElement(name = "TPA_Extensions")
    protected TPAExtensionsType tpaExtensions;
    @XmlAttribute(name = "RequestType")
    protected HotelComponentSearchType requestType;

    /**
     * Gets the value of the hotelSearchCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link HotelSearchCriteriaType }
     *     
     */
    public HotelSearchCriteriaType getHotelSearchCriteria() {
        return hotelSearchCriteria;
    }

    /**
     * Sets the value of the hotelSearchCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelSearchCriteriaType }
     *     
     */
    public void setHotelSearchCriteria(HotelSearchCriteriaType value) {
        this.hotelSearchCriteria = value;
    }

    /**
     * Gets the value of the hotelReservationIDs property.
     * 
     * @return
     *     possible object is
     *     {@link HotelReservationIDsType }
     *     
     */
    public HotelReservationIDsType getHotelReservationIDs() {
        return hotelReservationIDs;
    }

    /**
     * Sets the value of the hotelReservationIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelReservationIDsType }
     *     
     */
    public void setHotelReservationIDs(HotelReservationIDsType value) {
        this.hotelReservationIDs = value;
    }

    /**
     * Gets the value of the tpaExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link TPAExtensionsType }
     *     
     */
    public TPAExtensionsType getTPAExtensions() {
        return tpaExtensions;
    }

    /**
     * Sets the value of the tpaExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPAExtensionsType }
     *     
     */
    public void setTPAExtensions(TPAExtensionsType value) {
        this.tpaExtensions = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link HotelComponentSearchType }
     *     
     */
    public HotelComponentSearchType getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HotelComponentSearchType }
     *     
     */
    public void setRequestType(HotelComponentSearchType value) {
        this.requestType = value;
    }

}
