//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.14 at 01:53:08  GMT+08:00 
//


package org.opentravel.ota._2003._05;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.opentravel.org/OTA/2003/05}POS_Type">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ProcessingInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="SummaryResultsInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="DisplayCurrency" type="{http://www.opentravel.org/OTA/2003/05}ISO4217" />
 *                 &lt;attribute name="MaxResultsQty" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Criteria" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="Location" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://www.opentravel.org/OTA/2003/05}AddressType">
 *                             &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}PositionGroup"/>
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Proximity" maxOccurs="99" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.opentravel.org/OTA/2003/05>StringLength0to64">
 *                             &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}DistanceAttributesGroup"/>
 *                             &lt;attribute name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                             &lt;attribute name="CityName" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" />
 *                             &lt;attribute name="StateProv" type="{http://www.opentravel.org/OTA/2003/05}StateProvCodeType" />
 *                             &lt;attribute name="CountryCode" type="{http://www.opentravel.org/OTA/2003/05}ISO3166" />
 *                             &lt;attribute name="ResortName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="RefPointType" type="{http://www.opentravel.org/OTA/2003/05}OTA_CodeType" />
 *                             &lt;attribute name="Name" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                   &lt;element name="Features" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="DrivingRangeInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="DiningInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="GolfProInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="CourseDesigner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Amenities" type="{http://www.opentravel.org/OTA/2003/05}GolfAmenitySummaryType" maxOccurs="99" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" type="{http://www.opentravel.org/OTA/2003/05}StringLength0to32" />
 *                 &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.opentravel.org/OTA/2003/05}TPA_Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}OTA_PayloadStdAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pos",
    "processingInfo",
    "criteria",
    "tpaExtensions"
})
@XmlRootElement(name = "OTA_GolfCourseSearchRQ")
public class OTAGolfCourseSearchRQ {

    @XmlElement(name = "POS")
    protected OTAGolfCourseSearchRQ.POS pos;
    @XmlElement(name = "ProcessingInfo")
    protected OTAGolfCourseSearchRQ.ProcessingInfo processingInfo;
    @XmlElement(name = "Criteria")
    protected OTAGolfCourseSearchRQ.Criteria criteria;
    @XmlElement(name = "TPA_Extensions")
    protected TPAExtensionsType tpaExtensions;
    @XmlAttribute(name = "EchoToken")
    protected String echoToken;
    @XmlAttribute(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlAttribute(name = "Target")
    protected String target;
    @XmlAttribute(name = "TargetName")
    protected String targetName;
    @XmlAttribute(name = "Version", required = true)
    protected BigDecimal version;
    @XmlAttribute(name = "TransactionIdentifier")
    protected String transactionIdentifier;
    @XmlAttribute(name = "SequenceNmbr")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sequenceNmbr;
    @XmlAttribute(name = "TransactionStatusCode")
    protected String transactionStatusCode;
    @XmlAttribute(name = "RetransmissionIndicator")
    protected Boolean retransmissionIndicator;
    @XmlAttribute(name = "CorrelationID")
    protected String correlationID;
    @XmlAttribute(name = "PrimaryLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String primaryLangID;
    @XmlAttribute(name = "AltLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String altLangID;

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link OTAGolfCourseSearchRQ.POS }
     *     
     */
    public OTAGolfCourseSearchRQ.POS getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTAGolfCourseSearchRQ.POS }
     *     
     */
    public void setPOS(OTAGolfCourseSearchRQ.POS value) {
        this.pos = value;
    }

    /**
     * Gets the value of the processingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link OTAGolfCourseSearchRQ.ProcessingInfo }
     *     
     */
    public OTAGolfCourseSearchRQ.ProcessingInfo getProcessingInfo() {
        return processingInfo;
    }

    /**
     * Sets the value of the processingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTAGolfCourseSearchRQ.ProcessingInfo }
     *     
     */
    public void setProcessingInfo(OTAGolfCourseSearchRQ.ProcessingInfo value) {
        this.processingInfo = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link OTAGolfCourseSearchRQ.Criteria }
     *     
     */
    public OTAGolfCourseSearchRQ.Criteria getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTAGolfCourseSearchRQ.Criteria }
     *     
     */
    public void setCriteria(OTAGolfCourseSearchRQ.Criteria value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the tpaExtensions property.
     * 
     * @return
     *     possible object is
     *     {@link TPAExtensionsType }
     *     
     */
    public TPAExtensionsType getTPAExtensions() {
        return tpaExtensions;
    }

    /**
     * Sets the value of the tpaExtensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPAExtensionsType }
     *     
     */
    public void setTPAExtensions(TPAExtensionsType value) {
        this.tpaExtensions = value;
    }

    /**
     * Gets the value of the echoToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEchoToken() {
        return echoToken;
    }

    /**
     * Sets the value of the echoToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEchoToken(String value) {
        this.echoToken = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the targetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * Sets the value of the targetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetName(String value) {
        this.targetName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the transactionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * Gets the value of the sequenceNmbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNmbr() {
        return sequenceNmbr;
    }

    /**
     * Sets the value of the sequenceNmbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNmbr(BigInteger value) {
        this.sequenceNmbr = value;
    }

    /**
     * Gets the value of the transactionStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionStatusCode() {
        return transactionStatusCode;
    }

    /**
     * Sets the value of the transactionStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionStatusCode(String value) {
        this.transactionStatusCode = value;
    }

    /**
     * Gets the value of the retransmissionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRetransmissionIndicator() {
        return retransmissionIndicator;
    }

    /**
     * Sets the value of the retransmissionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetransmissionIndicator(Boolean value) {
        this.retransmissionIndicator = value;
    }

    /**
     * Gets the value of the correlationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationID() {
        return correlationID;
    }

    /**
     * Sets the value of the correlationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationID(String value) {
        this.correlationID = value;
    }

    /**
     * Gets the value of the primaryLangID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryLangID() {
        return primaryLangID;
    }

    /**
     * Sets the value of the primaryLangID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryLangID(String value) {
        this.primaryLangID = value;
    }

    /**
     * Gets the value of the altLangID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltLangID() {
        return altLangID;
    }

    /**
     * Sets the value of the altLangID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltLangID(String value) {
        this.altLangID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="Location" minOccurs="0">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;extension base="{http://www.opentravel.org/OTA/2003/05}AddressType">
     *                   &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}PositionGroup"/>
     *                 &lt;/extension>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="Proximity" maxOccurs="99" minOccurs="0">
     *             &lt;complexType>
     *               &lt;simpleContent>
     *                 &lt;extension base="&lt;http://www.opentravel.org/OTA/2003/05>StringLength0to64">
     *                   &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}DistanceAttributesGroup"/>
     *                   &lt;attribute name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                   &lt;attribute name="CityName" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" />
     *                   &lt;attribute name="StateProv" type="{http://www.opentravel.org/OTA/2003/05}StateProvCodeType" />
     *                   &lt;attribute name="CountryCode" type="{http://www.opentravel.org/OTA/2003/05}ISO3166" />
     *                   &lt;attribute name="ResortName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="RefPointType" type="{http://www.opentravel.org/OTA/2003/05}OTA_CodeType" />
     *                   &lt;attribute name="Name" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
     *                 &lt;/extension>
     *               &lt;/simpleContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *         &lt;element name="Features" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="DrivingRangeInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="DiningInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="GolfProInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="CourseDesigner" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Amenities" type="{http://www.opentravel.org/OTA/2003/05}GolfAmenitySummaryType" maxOccurs="99" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" type="{http://www.opentravel.org/OTA/2003/05}StringLength0to32" />
     *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "location",
        "proximity",
        "features",
        "amenities"
    })
    public static class Criteria {

        @XmlElement(name = "Location")
        protected OTAGolfCourseSearchRQ.Criteria.Location location;
        @XmlElement(name = "Proximity")
        protected List<OTAGolfCourseSearchRQ.Criteria.Proximity> proximity;
        @XmlElement(name = "Features")
        protected OTAGolfCourseSearchRQ.Criteria.Features features;
        @XmlElement(name = "Amenities")
        protected List<GolfAmenitySummaryType> amenities;
        @XmlAttribute(name = "ID")
        protected String id;
        @XmlAttribute(name = "Name")
        protected String name;

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link OTAGolfCourseSearchRQ.Criteria.Location }
         *     
         */
        public OTAGolfCourseSearchRQ.Criteria.Location getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTAGolfCourseSearchRQ.Criteria.Location }
         *     
         */
        public void setLocation(OTAGolfCourseSearchRQ.Criteria.Location value) {
            this.location = value;
        }

        /**
         * Gets the value of the proximity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the proximity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProximity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OTAGolfCourseSearchRQ.Criteria.Proximity }
         * 
         * 
         */
        public List<OTAGolfCourseSearchRQ.Criteria.Proximity> getProximity() {
            if (proximity == null) {
                proximity = new ArrayList<OTAGolfCourseSearchRQ.Criteria.Proximity>();
            }
            return this.proximity;
        }

        /**
         * Gets the value of the features property.
         * 
         * @return
         *     possible object is
         *     {@link OTAGolfCourseSearchRQ.Criteria.Features }
         *     
         */
        public OTAGolfCourseSearchRQ.Criteria.Features getFeatures() {
            return features;
        }

        /**
         * Sets the value of the features property.
         * 
         * @param value
         *     allowed object is
         *     {@link OTAGolfCourseSearchRQ.Criteria.Features }
         *     
         */
        public void setFeatures(OTAGolfCourseSearchRQ.Criteria.Features value) {
            this.features = value;
        }

        /**
         * Gets the value of the amenities property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the amenities property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAmenities().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GolfAmenitySummaryType }
         * 
         * 
         */
        public List<GolfAmenitySummaryType> getAmenities() {
            if (amenities == null) {
                amenities = new ArrayList<GolfAmenitySummaryType>();
            }
            return this.amenities;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="DrivingRangeInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="DiningInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="GolfProInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="CourseDesigner" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Features {

            @XmlAttribute(name = "DrivingRangeInd")
            protected Boolean drivingRangeInd;
            @XmlAttribute(name = "DiningInd")
            protected Boolean diningInd;
            @XmlAttribute(name = "GolfProInd")
            protected Boolean golfProInd;
            @XmlAttribute(name = "CourseDesigner")
            protected String courseDesigner;

            /**
             * Gets the value of the drivingRangeInd property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isDrivingRangeInd() {
                return drivingRangeInd;
            }

            /**
             * Sets the value of the drivingRangeInd property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDrivingRangeInd(Boolean value) {
                this.drivingRangeInd = value;
            }

            /**
             * Gets the value of the diningInd property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isDiningInd() {
                return diningInd;
            }

            /**
             * Sets the value of the diningInd property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDiningInd(Boolean value) {
                this.diningInd = value;
            }

            /**
             * Gets the value of the golfProInd property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isGolfProInd() {
                return golfProInd;
            }

            /**
             * Sets the value of the golfProInd property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGolfProInd(Boolean value) {
                this.golfProInd = value;
            }

            /**
             * Gets the value of the courseDesigner property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCourseDesigner() {
                return courseDesigner;
            }

            /**
             * Sets the value of the courseDesigner property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCourseDesigner(String value) {
                this.courseDesigner = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05}AddressType">
         *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}PositionGroup"/>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Location
            extends AddressType
        {

            @XmlAttribute(name = "Latitude")
            protected String latitude;
            @XmlAttribute(name = "Longitude")
            protected String longitude;
            @XmlAttribute(name = "Altitude")
            protected String altitude;
            @XmlAttribute(name = "AltitudeUnitOfMeasureCode")
            protected String altitudeUnitOfMeasureCode;
            @XmlAttribute(name = "PositionAccuracyCode")
            protected String positionAccuracyCode;

            /**
             * Gets the value of the latitude property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLatitude(String value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLongitude(String value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the altitude property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAltitude() {
                return altitude;
            }

            /**
             * Sets the value of the altitude property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAltitude(String value) {
                this.altitude = value;
            }

            /**
             * Gets the value of the altitudeUnitOfMeasureCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAltitudeUnitOfMeasureCode() {
                return altitudeUnitOfMeasureCode;
            }

            /**
             * Sets the value of the altitudeUnitOfMeasureCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAltitudeUnitOfMeasureCode(String value) {
                this.altitudeUnitOfMeasureCode = value;
            }

            /**
             * Gets the value of the positionAccuracyCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPositionAccuracyCode() {
                return positionAccuracyCode;
            }

            /**
             * Sets the value of the positionAccuracyCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPositionAccuracyCode(String value) {
                this.positionAccuracyCode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.opentravel.org/OTA/2003/05>StringLength0to64">
         *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}DistanceAttributesGroup"/>
         *       &lt;attribute name="PostalCode" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="CityName" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" />
         *       &lt;attribute name="StateProv" type="{http://www.opentravel.org/OTA/2003/05}StateProvCodeType" />
         *       &lt;attribute name="CountryCode" type="{http://www.opentravel.org/OTA/2003/05}ISO3166" />
         *       &lt;attribute name="ResortName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="RefPointType" type="{http://www.opentravel.org/OTA/2003/05}OTA_CodeType" />
         *       &lt;attribute name="Name" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to128" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Proximity {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "PostalCode")
            @XmlSchemaType(name = "anySimpleType")
            protected String postalCode;
            @XmlAttribute(name = "CityName")
            protected String cityName;
            @XmlAttribute(name = "StateProv")
            protected String stateProv;
            @XmlAttribute(name = "CountryCode")
            protected String countryCode;
            @XmlAttribute(name = "ResortName")
            protected String resortName;
            @XmlAttribute(name = "RefPointType")
            protected String refPointType;
            @XmlAttribute(name = "Name")
            protected String name;
            @XmlAttribute(name = "Distance")
            protected String distance;
            @XmlAttribute(name = "DistanceMeasure")
            protected String distanceMeasure;
            @XmlAttribute(name = "Direction")
            protected String direction;
            @XmlAttribute(name = "DistanceMax")
            protected String distanceMax;
            @XmlAttribute(name = "UnitOfMeasureCode")
            protected String unitOfMeasureCode;

            /**
             * Used for Character Strings, length 0 to 64.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the postalCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPostalCode() {
                return postalCode;
            }

            /**
             * Sets the value of the postalCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPostalCode(String value) {
                this.postalCode = value;
            }

            /**
             * Gets the value of the cityName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCityName() {
                return cityName;
            }

            /**
             * Sets the value of the cityName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCityName(String value) {
                this.cityName = value;
            }

            /**
             * Gets the value of the stateProv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStateProv() {
                return stateProv;
            }

            /**
             * Sets the value of the stateProv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStateProv(String value) {
                this.stateProv = value;
            }

            /**
             * Gets the value of the countryCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountryCode() {
                return countryCode;
            }

            /**
             * Sets the value of the countryCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountryCode(String value) {
                this.countryCode = value;
            }

            /**
             * Gets the value of the resortName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResortName() {
                return resortName;
            }

            /**
             * Sets the value of the resortName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResortName(String value) {
                this.resortName = value;
            }

            /**
             * Gets the value of the refPointType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefPointType() {
                return refPointType;
            }

            /**
             * Sets the value of the refPointType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefPointType(String value) {
                this.refPointType = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the distance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDistance() {
                return distance;
            }

            /**
             * Sets the value of the distance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDistance(String value) {
                this.distance = value;
            }

            /**
             * Gets the value of the distanceMeasure property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDistanceMeasure() {
                return distanceMeasure;
            }

            /**
             * Sets the value of the distanceMeasure property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDistanceMeasure(String value) {
                this.distanceMeasure = value;
            }

            /**
             * Gets the value of the direction property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDirection() {
                return direction;
            }

            /**
             * Sets the value of the direction property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDirection(String value) {
                this.direction = value;
            }

            /**
             * Gets the value of the distanceMax property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDistanceMax() {
                return distanceMax;
            }

            /**
             * Sets the value of the distanceMax property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDistanceMax(String value) {
                this.distanceMax = value;
            }

            /**
             * Gets the value of the unitOfMeasureCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnitOfMeasureCode() {
                return unitOfMeasureCode;
            }

            /**
             * Sets the value of the unitOfMeasureCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnitOfMeasureCode(String value) {
                this.unitOfMeasureCode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05}POS_Type">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class POS
        extends POSType
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="SummaryResultsInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="DisplayCurrency" type="{http://www.opentravel.org/OTA/2003/05}ISO4217" />
     *       &lt;attribute name="MaxResultsQty" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ProcessingInfo {

        @XmlAttribute(name = "SummaryResultsInd")
        protected Boolean summaryResultsInd;
        @XmlAttribute(name = "DisplayCurrency")
        protected String displayCurrency;
        @XmlAttribute(name = "MaxResultsQty")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger maxResultsQty;

        /**
         * Gets the value of the summaryResultsInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSummaryResultsInd() {
            return summaryResultsInd;
        }

        /**
         * Sets the value of the summaryResultsInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSummaryResultsInd(Boolean value) {
            this.summaryResultsInd = value;
        }

        /**
         * Gets the value of the displayCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayCurrency() {
            return displayCurrency;
        }

        /**
         * Sets the value of the displayCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayCurrency(String value) {
            this.displayCurrency = value;
        }

        /**
         * Gets the value of the maxResultsQty property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMaxResultsQty() {
            return maxResultsQty;
        }

        /**
         * Sets the value of the maxResultsQty property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMaxResultsQty(BigInteger value) {
            this.maxResultsQty = value;
        }

    }

}
