//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.06 at 10:20:21 pm CST 
//


package com.ccm.api.model.availability.req;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.net.chinaonline.webservices.availability package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StartDate_QNAME = new QName("http://webservices.micros.com/og/4.3/HotelCommon/", "StartDate");
    private final static QName _EndDate_QNAME = new QName("http://webservices.micros.com/og/4.3/HotelCommon/", "EndDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.net.chinaonline.webservices.availability
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AvailRequestSegment }
     * 
     */
    public AvailRequestSegment createAvailRequestSegment() {
        return new AvailRequestSegment();
    }

    /**
     * Create an instance of {@link Envelope }
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link RatePlanCandidates }
     * 
     */
    public RatePlanCandidates createRatePlanCandidates() {
        return new RatePlanCandidates();
    }

    /**
     * Create an instance of {@link Origin }
     * 
     */
    public Origin createOrigin() {
        return new Origin();
    }

    /**
     * Create an instance of {@link OGHeader }
     * 
     */
    public OGHeader createOGHeader() {
        return new OGHeader();
    }

    /**
     * Create an instance of {@link AvailabilityRequest }
     * 
     */
    public AvailabilityRequest createAvailabilityRequest() {
        return new AvailabilityRequest();
    }

    /**
     * Create an instance of {@link Criterion }
     * 
     */
    public Criterion createCriterion() {
        return new Criterion();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link HotelRef }
     * 
     */
    public HotelRef createHotelRef() {
        return new HotelRef();
    }

    /**
     * Create an instance of {@link HotelSearchCriteria }
     * 
     */
    public HotelSearchCriteria createHotelSearchCriteria() {
        return new HotelSearchCriteria();
    }

    /**
     * Create an instance of {@link RatePlanCandidate }
     * 
     */
    public RatePlanCandidate createRatePlanCandidate() {
        return new RatePlanCandidate();
    }

    /**
     * Create an instance of {@link Destination }
     * 
     */
    public Destination createDestination() {
        return new Destination();
    }

    /**
     * Create an instance of {@link StayDateRange }
     * 
     */
    public StayDateRange createStayDateRange() {
        return new StayDateRange();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.micros.com/og/4.3/HotelCommon/", name = "StartDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStartDate(String value) {
        return new JAXBElement<String>(_StartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservices.micros.com/og/4.3/HotelCommon/", name = "EndDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createEndDate(String value) {
        return new JAXBElement<String>(_EndDate_QNAME, String.class, null, value);
    }

}
